# Generated by Django 4.2.7 on 2023-11-17 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(max_length=255)),
                ('release', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('email', models.EmailField(max_length=255)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='electronics_retail.address')),
            ],
        ),
        migrations.CreateModel(
            name='Retail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('debt', models.DecimalField(decimal_places=2, max_digits=20)),
                ('type', models.CharField(choices=[('FC', 'Factory'), ('DB', 'Distributor'), ('DL', 'Dealer'), ('LR', 'Large Retail'), ('IE', 'Individual Entrepreneur')], max_length=2)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(to='electronics_retail.product')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='electronics_retail.contact')),
            ],
        ),
    ]
